<?php

namespace MailPoetVendor;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInitf676e2835b5e9b5574e79ff8c6b53ce3::getLoader();
